---

- name: "configure pipelines"
  template:
    src: files/pipelines.jinja2
    dest: "{{ logstash_config_dir }}/pipelines.yml"
    owner: "{{ logstash_config_owner | default('logstash') }}"
    group: "{{ logstash_config_owner | default('logstash') }}"
    mode: 0640
