---

- name: add elastic signing key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add logstash repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ logstash_version }}/apt stable main"
    state: present
    filename: logstash

- name: install logstash from repo
  apt:
    name: logstash
    state: installed
