---
# handlers file for logstash

- name: restart logstash
  service: 
    name: "{{ logstash_service_name | default('logstash.service') }}" 
    state: restarted 
    enabled: yes
  when: ansible_service_mgr == 'systemd'
